version: "3.9"

services:
    db:
        image: postgres:16
        container_name: cards-db
        restart: always
        env_file:
            - .env
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql/data

    app:
        build: .
        container_name: cards-app
        restart: always
        env_file:
            - .env
        environment:
            SPRING_PROFILES_ACTIVE: dev
            DB_HOST: db
            DB_PORT: 5432
        depends_on:
            - db
        ports:
            - "8080:8080"

volumes:
    db-data:
