spring:
    application:
        name: bank-cards-system

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USER}
        password: ${DB_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    liquibase:
        change-log: classpath:db/migration/db.changelog-master.yaml

server:
    port: 8080

jwt:
    secret: ${JWT_SECRET}
    ttl-min: ${JWT_TTL_MIN:60}

encryption:
    key: ${ENC_KEY_BASE64}

springdoc:
    api-docs:
        enabled: true
        path: /v3/api-docs
    swagger-ui:
        enabled: true
        path: /swagger-ui
